name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: w4153-cloud-computing
  REGION: us-east4
  GAR_LOCATION: us-east4-docker.pkg.dev/w4153-cloud-computing/w6998-backend/github-actions-build
  CR_SERVICE_NAME: w6998-backend-2

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Google github actions authentication"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Docker auth"
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Prepare Environment"
        run: echo "${{ secrets.YAML_SECRETS }}" >> secrets.yaml

      - name: "Build image"
        run: docker build . --file ./Dockerfile --tag "${{ env.GAR_LOCATION }}"

      - name: "Push Docker image to Artifact Registry"
        run: docker push "${{ env.GAR_LOCATION }}"

      - name: "Deploy to Google Cloud Run"
        run: |
          gcloud run deploy ${{ env.CR_SERVICE_NAME }} \
            --image "${{ env.GAR_LOCATION }}" \
            --region ${{ env.REGION }} \
            --min-instances 1 \
            --allow-unauthenticated \
            --env-vars-file secrets.yaml \
            --port=8010

      - name: "Clean Up"
        run: rm secrets.yaml
